version: '3'
services:
  netcat-listener:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      kafka-network:
        ipv4_address: 172.18.0.30
    container_name: netcat-listener

networks:
  kafka-network:
    external: true
