version: '3'

networks:
  kafka-network:
    name: kafka-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
        
services:
  consumer-python:
    # image: kafka-server
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consumer-python
    networks:
      kafka-network:
        ipv4_address: 172.18.0.14
    # command: [""]
    restart: 'no'
